import type { PortfolioData } from "@/types";

export const fallbackPortfolioData: PortfolioData = {
  personalInfo: {
    _id: "personal-info",
    name: "Kishore B",
    role: "Frontend Developer",
    location: "Chennai, Tamil Nadu, India",
    experienceYears: "1.5+",
    resumeUrl: "/resume.pdf",
    isVisible: true,
  },
  hero: {
    _id: "hero",
    greeting: "Hello, I'm",
    headline: "Kishore B",
    subheadline:
      "I craft high-performance frontend experiences with React & Next.js — turning complex requirements into elegant, scalable interfaces.",
    ctaPrimary: { label: "View My Work", href: "#projects" },
    ctaSecondary: { label: "Get In Touch", href: "#contact" },
    stats: [
      { label: "Years Experience", value: "1.5", suffix: "+" },
      { label: "APIs Integrated", value: "200", suffix: "+" },
      { label: "Active Users Served", value: "3000", suffix: "+" },
    ],
    isVisible: true,
  },
  about: {
    _id: "about",
    title: "About Me",
    subtitle: "Building products that scale",
    content: [],
    highlights: [
      "Architected enterprise onboarding platforms from scratch",
      "Built dashboards serving 3,000+ real estate agents",
      "Integrated 200+ REST APIs with robust error handling",
      "Implemented RBAC, multilingual support, and payment systems",
    ],
    isVisible: true,
  },
  skills: [
    { _id: "s1", name: "React.js", category: "Frontend", proficiency: 90, order: 1, isVisible: true },
    { _id: "s2", name: "Next.js", category: "Frontend", proficiency: 88, order: 2, isVisible: true },
    { _id: "s3", name: "TypeScript", category: "Language", proficiency: 85, order: 3, isVisible: true },
    { _id: "s4", name: "Tailwind CSS", category: "Styling", proficiency: 92, order: 4, isVisible: true },
    { _id: "s5", name: "Node.js", category: "Backend", proficiency: 70, order: 5, isVisible: true },
  ],
  technologies: [
    { _id: "t1", name: "React.js", category: "Frontend", order: 1, isVisible: true },
    { _id: "t2", name: "Next.js", category: "Frontend", order: 2, isVisible: true },
    { _id: "t3", name: "TypeScript", category: "Language", order: 3, isVisible: true },
    { _id: "t4", name: "JavaScript", category: "Language", order: 4, isVisible: true },
    { _id: "t5", name: "Tailwind CSS", category: "Styling", order: 5, isVisible: true },
    { _id: "t6", name: "Shadcn UI", category: "UI Library", order: 6, isVisible: true },
    { _id: "t7", name: "Chakra UI", category: "UI Library", order: 7, isVisible: true },
    { _id: "t8", name: "TanStack Query", category: "Data", order: 8, isVisible: true },
    { _id: "t9", name: "React Hook Form", category: "Forms", order: 9, isVisible: true },
    { _id: "t10", name: "Redux Toolkit", category: "State", order: 10, isVisible: true },
    { _id: "t11", name: "Zustand", category: "State", order: 11, isVisible: true },
    { _id: "t12", name: "Node.js", category: "Backend", order: 12, isVisible: true },
    { _id: "t13", name: "Express.js", category: "Backend", order: 13, isVisible: true },
    { _id: "t14", name: "MongoDB", category: "Database", order: 14, isVisible: true },
    { _id: "t15", name: "Sanity CMS", category: "CMS", order: 15, isVisible: true },
    { _id: "t16", name: "Stripe", category: "Payments", order: 16, isVisible: true },
    { _id: "t17", name: "Razorpay", category: "Payments", order: 17, isVisible: true },
    { _id: "t18", name: "Framer Motion", category: "Animation", order: 18, isVisible: true },
    { _id: "t19", name: "Vercel", category: "DevOps", order: 19, isVisible: true },
    { _id: "t20", name: "AWS S3", category: "Cloud", order: 20, isVisible: true },
  ],
  experiences: [
    {
      _id: "exp1",
      company: "Cyces Innovation Labs LLP",
      role: "Frontend Developer",
      location: "Chennai, India",
      startDate: "2025-01",
      isCurrent: true,
      responsibilities: [
        "Built the Realty of America Onboarding Platform from scratch, serving 3,000+ real estate agents",
        "Developed the Agent Dashboard with real-time data visualization and role-based access control",
        "Contributed to the Admin Panel with complex data management workflows",
        "Integrated 200+ REST APIs with comprehensive error handling and loading states",
        "Implemented multilingual support across the entire platform",
        "Integrated Stripe payments, Twilio communications, and Sanity CMS",
        "Configured Google Analytics, CookieYes, and Sentry for monitoring",
        "Managed Vercel deployments and established reusable frontend architecture",
      ],
      technologies: [
        "React.js",
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Stripe",
        "Twilio",
        "Sanity CMS",
        "Sentry",
        "Vercel",
      ],
      order: 1,
      isVisible: true,
    },
    {
      _id: "exp2",
      company: "Murven Infotech Design Solutions LLP",
      role: "Software Development Intern",
      location: "Chennai, India",
      startDate: "2024-01",
      endDate: "2024-12",
      isCurrent: false,
      responsibilities: [
        "Built a full-stack MERN E-Commerce application with product catalog and cart management",
        "Integrated Razorpay payment gateway for secure checkout flows",
        "Created RESTful APIs with Express.js and MongoDB",
        "Developed reusable UI components with responsive design patterns",
      ],
      technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Razorpay"],
      order: 2,
      isVisible: true,
    },
  ],
  projects: [
    {
      _id: "proj1",
      title: "Social Media Application",
      slug: "social-media-app",
      description:
        "A full-featured social platform with real-time interactions, media sharing, and an intuitive feed experience built for performance at scale.",
      techStack: ["React.js", "Node.js", "MongoDB", "REST APIs", "Tailwind CSS"],
      githubUrl: "https://github.com/kishoreb",
      featured: true,
      order: 1,
      isVisible: true,
    },
    {
      _id: "proj2",
      title: "Portfolio Website",
      slug: "portfolio-website",
      description:
        "A premium developer portfolio with CMS integration, animated sections, and enterprise-grade architecture — built with Next.js, Sanity, and Framer Motion.",
      techStack: ["Next.js", "TypeScript", "Sanity CMS", "Framer Motion", "Tailwind CSS"],
      liveUrl: "https://kishoreb.dev",
      featured: true,
      order: 2,
      isVisible: true,
    },
  ],
  education: [],
  achievements: [],
  services: [
    {
      _id: "svc1",
      title: "Frontend Development",
      description:
        "Building responsive, accessible, and performant user interfaces with modern React ecosystems.",
      order: 1,
      isVisible: true,
    },
    {
      _id: "svc2",
      title: "UI Architecture",
      description:
        "Designing scalable component libraries and design systems for enterprise applications.",
      order: 2,
      isVisible: true,
    },
    {
      _id: "svc3",
      title: "API Integration",
      description:
        "Seamlessly connecting frontend applications with REST APIs, payment gateways, and third-party services.",
      order: 3,
      isVisible: true,
    },
  ],
  testimonials: [],
  socialLinks: [
    { _id: "soc1", platform: "GitHub", url: "https://github.com/kishoreb", icon: "github", order: 1, isVisible: true },
    { _id: "soc2", platform: "LinkedIn", url: "https://linkedin.com/in/kishoreb", icon: "linkedin", order: 2, isVisible: true },
  ],
  contact: {
    _id: "contact",
    email: "kishore@example.com",
    location: "Chennai, Tamil Nadu, India",
    availability: "Open to opportunities",
    isVisible: true,
  },
  navigation: [
    { _id: "nav1", label: "Home", href: "#hero", order: 1, isVisible: true },
    { _id: "nav2", label: "About", href: "#about", order: 2, isVisible: true },
    { _id: "nav3", label: "Experience", href: "#experience", order: 3, isVisible: true },
    { _id: "nav4", label: "Skills", href: "#skills", order: 4, isVisible: true },
    { _id: "nav5", label: "Projects", href: "#projects", order: 5, isVisible: true },
    { _id: "nav6", label: "Contact", href: "#contact", order: 6, isVisible: true },
  ],
  footer: {
    _id: "footer",
    copyright: `© ${new Date().getFullYear()} Kishore B. All rights reserved.`,
    tagline: "Crafted with precision. Built to impress.",
    isVisible: true,
  },
  seo: {
    _id: "seo",
    defaultTitle: "Kishore B — Frontend Developer",
    defaultDescription:
      "Frontend Developer specializing in React, Next.js, and TypeScript. Building scalable web applications for enterprise platforms.",
    keywords: [
      "Kishore B",
      "Frontend Developer",
      "React",
      "Next.js",
      "TypeScript",
      "Chennai",
    ],
  },
};
