import type { PortfolioData } from "@/types";

export const fallbackPortfolioData: PortfolioData = {
  personalInfo: {
    _id: "personalInfo",
    name: "Kishore B",
    email: "kishore@example.com",
    phone: "+91 00000 00000",
    role: "Frontend Developer",
    experienceYears: "1.5+",
    location: "Chennai, Tamil Nadu, India",
    heroDescription:
      "Building modern frontend experiences with React, Next.js & Node.js, where clean design meets scalable engineering.",
    linkedinUrl: "https://linkedin.com/in/kishoreb",
    instagramUrl: "https://instagram.com/kishoreb",
    resumeUrl: "/resume.pdf",
    availability: "Open to opportunities",
    isVisible: true,
  },
  about: {
    _id: "aboutSection",
    title: "About Me",
    subtitle:
      "Building modern web products with clean design and scalable engineering.",
    description:
      "I build modern websites and web applications that combine thoughtful design, intuitive user experiences, and scalable engineering. From crafting polished frontend interfaces to developing reliable backend services with Node.js, I focus on creating fast, maintainable, and production-ready products that deliver exceptional user experiences.",
    highlights: [
      {
        title: "Modern Website & Web App Development",
        description:
          "Building responsive, scalable websites and applications that deliver seamless digital experiences.",
        icon: "globe",
      },
      {
        title: "Thoughtful UI & User Experience",
        description:
          "Creating clean, intuitive interfaces that balance aesthetics, usability, and accessibility.",
        icon: "palette",
      },
      {
        title: "Scalable Backend Development",
        description:
          "Developing reliable Node.js services and APIs that power secure, high-performance applications.",
        icon: "server",
      },
      {
        title: "Performance & Quality Focused",
        description:
          "Optimising every project for speed, maintainability, and long-term scalability.",
        icon: "zap",
      },
    ],
    isVisible: true,
  },
  experiences: [
    {
      _id: "exp1",
      company: "Cyces Innovation Labs LLP",
      role: "Frontend Developer",
      location: "Chennai, India",
      startDate: "2025-01",
      isCurrent: true,
      responsibilities: [
        "Built the Realty of America Onboarding Platform from scratch, serving 3,000+ real estate agents",
        "Developed the Agent Dashboard with real-time data visualization and role-based access control",
        "Contributed to the Admin Panel with complex data management workflows",
        "Integrated 200+ REST APIs with comprehensive error handling and loading states",
        "Implemented multilingual support across the entire platform",
        "Integrated Stripe payments, Twilio communications, and Sanity CMS",
        "Configured Google Analytics, CookieYes, and Sentry for monitoring",
        "Managed Vercel deployments and established reusable frontend architecture",
      ],
      technologies: [
        "React.js",
        "Next.js",
        "TypeScript",
        "Tailwind CSS",
        "Stripe",
        "Twilio",
        "Sanity CMS",
        "Sentry",
        "Vercel",
      ],
      order: 1,
      isVisible: true,
    },
    {
      _id: "exp2",
      company: "Murven Infotech Design Solutions LLP",
      role: "Software Development Intern",
      location: "Chennai, India",
      startDate: "2024-01",
      endDate: "2024-12",
      isCurrent: false,
      responsibilities: [
        "Built a full-stack MERN E-Commerce application with product catalog and cart management",
        "Integrated Razorpay payment gateway for secure checkout flows",
        "Created RESTful APIs with Express.js and MongoDB",
        "Developed reusable UI components with responsive design patterns",
      ],
      technologies: ["React.js", "Node.js", "Express.js", "MongoDB", "Razorpay"],
      order: 2,
      isVisible: true,
    },
  ],
  skills: [
    {
      _id: "s1",
      name: "React.js",
      tag: { _id: "tag-frontend", title: "Frontend", orderRank: "a0" },
      orderRank: "a0",
      isVisible: true,
    },
    {
      _id: "s2",
      name: "Next.js",
      tag: { _id: "tag-frontend", title: "Frontend", orderRank: "a0" },
      orderRank: "a1",
      isVisible: true,
    },
    {
      _id: "s3",
      name: "TypeScript",
      tag: { _id: "tag-frontend", title: "Frontend", orderRank: "a0" },
      orderRank: "a2",
      isVisible: true,
    },
    {
      _id: "s4",
      name: "JavaScript",
      tag: { _id: "tag-frontend", title: "Frontend", orderRank: "a0" },
      orderRank: "a3",
      isVisible: true,
    },
    {
      _id: "s5",
      name: "Tailwind CSS",
      tag: { _id: "tag-frontend", title: "Frontend", orderRank: "a0" },
      orderRank: "a4",
      isVisible: true,
    },
    {
      _id: "s6",
      name: "Shadcn UI",
      tag: { _id: "tag-frontend", title: "Frontend", orderRank: "a0" },
      orderRank: "a5",
      isVisible: true,
    },
    {
      _id: "s7",
      name: "Node.js",
      tag: { _id: "tag-backend", title: "Backend", orderRank: "a1" },
      orderRank: "a6",
      isVisible: true,
    },
    {
      _id: "s8",
      name: "Express.js",
      tag: { _id: "tag-backend", title: "Backend", orderRank: "a1" },
      orderRank: "a7",
      isVisible: true,
    },
    {
      _id: "s9",
      name: "MongoDB",
      tag: { _id: "tag-database", title: "Database", orderRank: "a2" },
      orderRank: "a8",
      isVisible: true,
    },
    {
      _id: "s10",
      name: "Sanity CMS",
      tag: { _id: "tag-tools", title: "Tools", orderRank: "a3" },
      orderRank: "a9",
      isVisible: true,
    },
    {
      _id: "s11",
      name: "Git",
      tag: { _id: "tag-tools", title: "Tools", orderRank: "a3" },
      orderRank: "b0",
      isVisible: true,
    },
    {
      _id: "s12",
      name: "Vercel",
      tag: { _id: "tag-tools", title: "Tools", orderRank: "a3" },
      orderRank: "b1",
      isVisible: true,
    },
  ],
  projects: [
    {
      _id: "proj1",
      title: "Social Media Application",
      description:
        "A full-featured social platform with real-time interactions, media sharing, and an intuitive feed experience built for performance at scale.",
      techStack: ["React.js", "Node.js", "MongoDB", "REST APIs", "Tailwind CSS"],
      githubUrl: "https://github.com/kishoreb",
      order: 1,
      isVisible: true,
    },
    {
      _id: "proj2",
      title: "Portfolio Website",
      description:
        "A premium developer portfolio with CMS integration, animated sections, and enterprise-grade architecture — built with Next.js, Sanity, and Framer Motion.",
      techStack: [
        "Next.js",
        "TypeScript",
        "Sanity CMS",
        "Framer Motion",
        "Tailwind CSS",
      ],
      liveUrl: "https://kishoreb.dev",
      order: 2,
      isVisible: true,
    },
  ],
};
