export type {
  AboutSection,
  Achievement,
  ContactInfo,
  Education,
  Experience,
  FooterContent,
  HeroSection,
  HeroStat,
  NavItem,
  PersonalInfo,
  PortfolioData,
  Project,
  ProjectCategory,
  ProjectTag,
  SanityImage,
  SeoFields,
  SeoSettings,
  Service,
  Skill,
  SocialLink,
  Technology,
  Testimonial,
  WebsiteSettings,
} from "./portfolio";
