export const siteConfig = {
  name: "Kishore B",
  title: "Kishore B — Frontend Developer | React, Next.js, Node.js",
  description:
    "Kishore B is a Frontend Developer in Chennai specializing in React.js, Next.js, Node.js, Express, MongoDB, and Figma. Available for freelance web development and full-stack product engineering.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://kishoreb.dev",
  locale: "en_IN",
  keywords: [
    "Kishore",
    "Kishore B",
    "Kishore Frontend Developer",
    "Kishore Developer",
    "Frontend Developer",
    "Front End Developer",
    "Frontend Developer Chennai",
    "Full Stack Developer",
    "React Developer",
    "React.js Developer",
    "React JS",
    "Next.js Developer",
    "Next JS",
    "Next.js Freelancer",
    "Node.js Developer",
    "Node JS",
    "Express.js",
    "Express JS",
    "MongoDB",
    "MongoDB Developer",
    "Figma",
    "Figma Designer",
    "TypeScript Developer",
    "JavaScript Developer",
    "MERN Stack Developer",
    "Freelance Developer",
    "Freelancing",
    "Freelance Frontend Developer",
    "Web Developer",
    "UI Engineer",
    "Hire Frontend Developer",
    "Chennai Developer",
    "Portfolio",
  ],
  author: {
    name: "Kishore B",
    alternateName: ["Kishore", "Kishore B Frontend Developer"],
    email: "kishore@example.com",
    url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://kishoreb.dev",
    jobTitle: "Frontend Developer",
    location: "Chennai, Tamil Nadu, India",
  },
  social: {
    linkedin: "https://linkedin.com/in/kishoreb",
    instagram: "https://instagram.com/kishoreb",
    email: "mailto:kishore@example.com",
  },
  knowsAbout: [
    "Frontend Development",
    "Full Stack Development",
    "React.js",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "Figma",
    "Tailwind CSS",
    "REST APIs",
    "Freelance Web Development",
    "UI Engineering",
    "Web Application Development",
  ],
  navigation: [
    { label: "Home", href: "/#hero" },
    { label: "About", href: "/#about" },
    { label: "Experience", href: "/#experience" },
    { label: "Skills", href: "/#skills" },
    { label: "Projects", href: "/projects" },
    { label: "Blogs", href: "/blogs" },
    { label: "Contact", href: "/#contact" },
  ],
} as const;
